# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/softwinner/cubieboard1/extract-files.sh - DO NOT EDIT

# All the blobs necessary for softwinner/cubieboard1
PRODUCT_COPY_FILES += \
    vendor/softwinner/cubieboard1/proprietary/libMali.so:system/lib/libMali.so \
    vendor/softwinner/cubieboard1/proprietary/libUMP.so:system/lib/libUMP.so \
    vendor/softwinner/cubieboard1/proprietary/liballwinner-ril.so:system/lib/liballwinner-ril.so \
    vendor/softwinner/cubieboard1/proprietary/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/softwinner/cubieboard1/proprietary/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/softwinner/cubieboard1/proprietary/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/softwinner/cubieboard1/proprietary/gralloc.sun4i.so:system/lib/hw/gralloc.sun4i.so \
    vendor/softwinner/cubieboard1/proprietary/modules/8192cu.ko:system/lib/modules/8192cu.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/gc0308.ko:system/lib/modules/gc0308.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/hi253.ko:system/lib/modules/hi253.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/tea5761.ko:system/lib/modules/tea5761.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/videobuf-core.ko:system/lib/modules/videobuf-core.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/disp_ump.ko:system/lib/modules/disp_ump.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/gt2005.ko:system/lib/modules/gt2005.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/mali.ko:system/lib/modules/mali.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/sun4i_csi0.ko:system/lib/modules/sun4i_csi0.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/ump.ko:system/lib/modules/ump.ko \
    vendor/softwinner/cubieboard1/proprietary/modules/videobuf-dma-contig.ko:system/lib/modules/videobuf-dma-contig.ko \
